apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-restserver
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/fabric-restserver
    git: https://github.com/pppazos/blockchain-automation-framework.git
    ref: local
  releaseName: carrier-restserver
  values:
    metadata:
      namespace: carrier-net
    server:
      name: carrier-restserver
      port: 20001
      localmspid: carrierMSP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:rest_server_latest
      username: admin
      cert_path: "/secret/tls/admin.cert"
      key_path: "/secret/tls/admin.pem"
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      address: http://192.168.0.13:8200
      role: vault-role
      authpath: carrier-net-auth
      secretprefix: secret/crypto/peerOrganizations/carrier-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: hyperledgerlabs/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.carrier-net
      peerAddress: peer0.carrier-net
      peerPort: 7051
      ordererAddress: orderer1.supplychain-net
      ordererPort: 7050