apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storestorequorum
  namespace: store-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: storestorequorum
  helmVersion: v3
  chart:
    git: ssh://git@github.com/pppazos/blockchain-automation-framework.git
    ref: gcp_quorum
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: store-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: store
      status: default
      consensus: ibft
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.gcp.iriago.com:20002
      secretprefix: secretsv2/data/store-quo/crypto/store
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumstore
    tessera:
      dburl: "jdbc:mysql://store-tessera:3306/demodb"
      dbusername: demouser
      url: "https://store.test.quorum.dev2.gcp.iriago.com:443"
      clienturl: "http://store-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://carrier.test.quorum.dev2.gcp.iriago.com
        - url: https://manufacturer.test.quorum.dev2.gcp.iriago.com
        - url: https://store.test.quorum.dev2.gcp.iriago.com
        - url: https://warehouse.test.quorum.dev2.gcp.iriago.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjE4OTU2ZjMiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDFiNjhlNzU4ZTYyMDY4MTEwODc1ODExZDBmN2U0NmFjOGU1NTQ2NWM5NDU0YTRkODg1Y2VlMGYzYjU3ODVhYTk3ODRjYzNkMDMwYTBiMzFjMGU5NDM0MzJkY2E3ODliOWQxYmE2MzhkNGQ3ZDlhZmQxODI1NzlkMGIwMGU5NDFlZjkxZGMwNzhkZWNjYWExMWExYWEyMzA3YmU4NGE3OGUzN2M5OTZiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICIxYjY4ZTc1OGU2MjA2ODExMDg3NTgxMWQwZjdlNDZhYzhlNTU0NjVjIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiMWVmOTFkYzA3OGRlY2NhYTExYTFhYTIzMDdiZTg0YTc4ZTM3Yzk5NiI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjM0MzJkY2E3ODliOWQxYmE2MzhkNGQ3ZDlhZmQxODI1NzlkMGIwMGUiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICI1NGE0ZDg4NWNlZTBmM2I1Nzg1YWE5Nzg0Y2MzZDAzMGEwYjMxYzBlIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://6d70380927988311bae06cd22c612f5cc87d44cbac544a51cea2613a9b938ee5c30e963f6f7ce6903ddcb37bf6fd3bb5df75f4baf85573a0cfff511469331b34@carrier.test.quorum.dev2.gcp.iriago.com:15030?discport=0",
    "enode://694528122746e7ad55f80fb0cc45fd84165a8104bc09b6d2218dee04714d8f2bb09207850b101d5f74b78e82ff993454858e80cabea82d5e4823158681178fa8@manufacturer.test.quorum.dev2.gcp.iriago.com:15033?discport=0",
    "enode://3244579c2f7c0c35832e1eb8b2ae1b29be4a06a642746707e76989ae901cd2c74bce3919702d5f05603a6a4a60d6d5074e59c20482c89a0dd364987535157376@store.test.quorum.dev2.gcp.iriago.com:15036?discport=0",
    "enode://280be0f2423fdb15b5490c7a97195beef9416282e6a4dc42324c6e53db5c5d12fdb01bd9352af67c3ba388ae8b9119299996bc96f32f3797e26d7f6088557634@warehouse.test.quorum.dev2.gcp.iriago.com:15039?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: store.test.quorum.dev2.gcp.iriago.com
      portTM: 443
      rpcport: 15037
      quorumport: 15036
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
