apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-manufacturer
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-manufacturer
  chart:
    git: https://github.com/pppazos/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://192.168.0.13:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CqwCChAKDggCIgphbGxjaGFubmVsEpcCCpQCCgphbGxjaGFubmVsEl8SXQoLQXBwbGljYXRpb24S
      TggBEkIKD21hbnVmYWN0dXJlck1TUBIvGgcKA01TUBIAIgoKBkFkbWlucxIAIgsKB1JlYWRlcnMS
      ACILCgdXcml0ZXJzEgAqBkFkbWlucxqkARKhAQoLQXBwbGljYXRpb24SkQEIARKEAQoPbWFudWZh
      Y3R1cmVyTVNQEnEIARo2CgtBbmNob3JQZWVycxInEh0KGwoWcGVlcjAubWFudWZhY3R1cmVyLW5l
      dBCLNxoGQWRtaW5zGgcKA01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACILCgdSZWFkZXJz
      EgAqBkFkbWlucyoGQWRtaW5z

