apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturermanufacturerquorum
  namespace: manufacturer-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturermanufacturerquorum
  helmVersion: v3
  chart:
    git: ssh://git@github.com/pppazos/blockchain-automation-framework.git
    ref: gcp_quorum
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: manufacturer-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.4.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: manufacturer
      status: default
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev.gcp.inteli-poc.com:20002
      secretprefix: secretsv2/data/manufacturer-quo/crypto/manufacturer
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummanufacturer
    tessera:
      dburl: "jdbc:mysql://manufacturer-tessera:3306/demodb"
      dbusername: demouser
      url: "https://manufacturer.test.quorum.dev.gcp.inteli-poc.com:443"
      clienturl: "http://manufacturer-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://carrier.test.quorum.dev.gcp.inteli-poc.com
        - url: https://manufacturer.test.quorum.dev.gcp.inteli-poc.com
        - url: https://store.test.quorum.dev.gcp.inteli-poc.com
        - url: https://warehouse.test.quorum.dev.gcp.inteli-poc.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjE4ZDJkYTYiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NGVhMWViYzU2MmJlMWMxYjMyNmRlOTI2Mzc4MzMwZmZjYzU3ZGQ3N2E5NDZjMzE4MDZkZDhkNjI5ZDJhZWJkZDc5OGVhZjAwMWFkMzA5NmM2NWU5NDA5OTMyZmRlMTA5ZjQzNzE4YTQ4MjgyZjRlMzBkZDEwOGNjNjFiZTU5NDY2ZDM2OTRkY2QxMDM3YTU0ZjMyNGI2ZGJlNTQ1ODNlNTQ2YzAwNWNiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICIwOTkzMmZkZTEwOWY0MzcxOGE0ODI4MmY0ZTMwZGQxMDhjYzYxYmU1IjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNjZkMzY5NGRjZDEwMzdhNTRmMzI0YjZkYmU1NDU4M2U1NDZjMDA1YyI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjZjMzE4MDZkZDhkNjI5ZDJhZWJkZDc5OGVhZjAwMWFkMzA5NmM2NWUiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJlYTFlYmM1NjJiZTFjMWIzMjZkZTkyNjM3ODMzMGZmY2M1N2RkNzdhIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://6342f12ab5ba1df588116d3a8d48ab8dceb52a6e10eb096c9297672f5ee23a27ffa3f14cbe43c52a3ebcc585d4978aa40a8da42414f78a8031f8f000e1ed2fe1@carrier.test.quorum.dev.gcp.inteli-poc.com:15030?discport=0",
    "enode://b6626065f1016ae59c5c4a19b3cbc014e3461a88704b9dccaaa76d90ea2f0c40628956c8c38ec6f6d2b4711286c1f6c22418e51815aaa214e264d891a19a6c5f@manufacturer.test.quorum.dev.gcp.inteli-poc.com:15033?discport=0",
    "enode://2fea9eb675a3fea9aa6e99aeb6261cf844a6250ece990ab57f73ac143511f9694489262d23f61f69ee52bf2dc0a1c5f95033ef91f9ff21911ca966bae09ce618@store.test.quorum.dev.gcp.inteli-poc.com:15036?discport=0",
    "enode://5c0c7c302a88a728adfcfee4d31d16e7fa06a6b5497575ca1190c6ae4ab544edffe0e47a801c39e1323a665e893f2fd08a96f266bff76d5c6ce2d866c447fc81@warehouse.test.quorum.dev.gcp.inteli-poc.com:15039?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: manufacturer.test.quorum.dev.gcp.inteli-poc.com
      portTM: 443
      rpcport: 15034
      quorumport: 15033
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
