---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    privilege_escalate: true            #escalate root priviledge for default test
    install_os: "linux"                 #Default to linux OS
    install_arch:  "amd64"              #Default to amd64 architecture
    bin_install_dir:  "~/bin"           
    kubeconfig_path: "/tmp/molecule/kind-default/kubeconfig"
    kubecontext: "kind"
    network:
      env:
        retry_count: 20                 # Retry count for the checks
  roles:
    - role: setup/kubectl
      vars:
        kubectl:
          version: "1.20.4"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: "sha256:a9f2dadcb4a721371e2db8cf25217925fed1a77bb2c2d28624c604ab6c3035db"
    - role: setup/helm
      vars:
        helm:
          version: "v3.2.4"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
    - role: setup/vault
      vars:
        vault:
          version: "1.0.1"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
    - role: setup/aws-auth
      vars:
        aws_authenticator:
          version: "1.10.3"
          release_date:  "2018-07-26"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
        item:
          aws:
            access_key: test
            secret_key: test
