###########################################################
# Playbook to create deployment files for the following:
#  storageclass
#  namespaces, service account and clusterrolebinding
# Playbook arguments: complete network.yaml
###########################################################
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
  # Delete build directory before start of play, can be commented if you do not want to delete it.

  # ---------------------------------------------------------------------- 
  # Setup CENM services for the network
  - name: "Setup cenm"   
    include_role: 
      name: "setup/cenm"
    vars:
      services: "{{ org.services }}"
      organisation: "{{ org.name | lower }}"
      component_ns: "{{ org.name | lower }}-ent"
      kubernetes: "{{ org.k8s }}"
      vault: "{{ org.vault }}"
      gitops: "{{ org.gitops }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: org
    when: org.type == 'cenm'
