apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-university-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-university-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: ssh://git@github.com/pppazos/blockchain-automation-framework.git
    ref: dev3
  values:
    metadata:
      name: university-university-trustee
      namespace: university-ns
    network:
      name: baf
    image:
      name: university
      repository: adopblockchaincloud0502.azurecr.io/indy-key-mgmt:1.12.1
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev3.aws.blockchaincloudpoc-develop.com:30001
      keyPath: university.trustees
      identity: university-trustee
      auth_path: kubernetes-university-admin-auth
    account:
      service: university-admin-vault-auth
      role: rw
