apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainvalidator3ibft
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator3ibft
  chart:
    git: ssh://git@github.com/pppazos/blockchain-automation-framework.git
    ref: gcp_quorum
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://5e5d6641646b0556085c98c5e6966ca0e6806203f84f3abd2e56baaf2ba075db8926d5d8801114d9a3089db3cfc03aa52b4de1ffec410f9471db7fcb9a199c24@validator1.bs.test.dev2.gcp.iriago.com:15010"
      
      - "enode://9a99716eeb0df0af5ea5d9d25910c06e8b6ad5fa4f42cf75d35b1bd838f150b7b70d0cbab2a1cfa4e8f0ae16c8d3bd6bfe44a06e2e83990ea18b2fe55e041dd3@validator2.bs.test.dev2.gcp.iriago.com:15012"
      
      - "enode://3b9a942e90b24b65da86e512cc2f627395bfd0dff8c9380595a38e5734d0a5d4f543cdb1f01f4f095b917e41d8787f7d8ecc02b3d6df2b3d670b8e1965be97db@validator3.bs.test.dev2.gcp.iriago.com:15014"
      
      - "enode://6a61e34d6105faab101c2de50b49beb0f1b891dcbf34141598903c2aede7cf2588dbf08d054b405cf78d544ccdf04e6c266194f95fc52080e740f961ed7356d9@validator4.bs.test.dev2.gcp.iriago.com:15016"
      
      - "enode://f2812e0e4a2bf077e595ea440da2d47132a340b180af1ab484d61fcae99be45114b95f47f227233dad23bbbe4d29459de0a4dbfa4ae42ca96da22c4916ffc936@carrier.bs.test.dev2.gcp.iriago.com:15020"
      
      - "enode://8a7a7ff8d591d70ae09178edd01a053474ad32c867b9417af650fd5eba8da73e168c442b3680380a29411535b0689e76de1aa7b1c7677953ab6c69fbb66268bc@manufacturer.bs.test.dev2.gcp.iriago.com:15030"
      
      - "enode://ab857dcaf6a613c4cac76c2de8c71cc58727459b1ee387811eda5e10626e94fe56f43df6f35a5f0aedd9bdd1e63289940697fc26fc08abd5c362a24f74a29f14@store.bs.test.dev2.gcp.iriago.com:15040"
      
      - "enode://f4c7d97457fb41148681972464d16804a5271eadc701bab697ae3b5c884a9d1d3c62578e78b00a0118e328aaa2830f84b825ac63eda91fb0cd7c886dfadbf2bc@warehouse.bs.test.dev2.gcp.iriago.com:15050"
      

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: bs.test.dev2.gcp.iriago.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychain.bs.test.dev2.gcp.iriago.com
      p2p: 15014
      rpc: 15015

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator3
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.gcp.iriago.com:20002
      secretprefix: secretsv2/data/supplychain-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDQ0YTJlY2IxY2I4MzI5ZjE2MjA3OTRhYWExODlmMTRlMWUwZThjNmU5NDZlN2FjZTc4OWI3ZDc1NjZkODA2ZmNhMGU1YWE5NmJmZGYyMTM0M2U5NDg1ZWE1OGU4MWE2NjVlMmJiNDg5YjhhODUxNTI0ZWQzMTlhZjkzNGI5NDk5ZmU5MzRkMTI4YjE2YTQ3YzcyOTNhZDM5NjMwNGIxYWVmMzhlMjk4MDg0MDAwMDAwMDBjMCIKfQ==
