apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/pppazos/blockchain-automation-framework.git
    ref: dev3
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"9mrLtZe1WfF16nrEVJmCrH","role":"0","verkey":"5nLmxCb1XiKnyReycuEejirBct7761dWVoxp5yqXBFzU"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"K7fBkMtvs2REYbPKyfhLjk","role":"0","verkey":"AsePAsQrQnbXYMYNuR4mrnkYN3GWQnHX9qCMW1Ne2hoZ"},"metadata":{"from":"9mrLtZe1WfF16nrEVJmCrH"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"ToC7cnEKeWuNiusvZAQV3y","role":"2","verkey":"Fc64YW6hs8weN7uatZExYECUZt8p6VafZTBRU1iRRSam"},"metadata":{"from":"K7fBkMtvs2REYbPKyfhLjk"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"AM5x467d5NfLBoLk7jMaT7","role":"2","verkey":"66TPPQTa6zPDVcBnxTChR1hw3VZenFDMaBxDmcZRbWZr"},"metadata":{"from":"K7fBkMtvs2REYbPKyfhLjk"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"WGZSu71KTGJpgRB19h5LBv","role":"0","verkey":"GxECbU585Xu6s6uGG3uLTBQuidw5zB2nJBycinsspi6v"},"metadata":{"from":"9mrLtZe1WfF16nrEVJmCrH"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"9ptRvZPdJzsu4CmCKVmyyj","role":"2","verkey":"5ozkQMNgjDPCZF7rXshciSYW2b3D6pxnY6PTpAhENzSP"},"metadata":{"from":"WGZSu71KTGJpgRB19h5LBv"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"QbST26PNW43ywpA7FxpDGh","role":"2","verkey":"Drr3jp63NbQtyYPN3nCmA57hzikwGeZxmw2tMkx36iR1"},"metadata":{"from":"WGZSu71KTGJpgRB19h5LBv"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
