# This is custom git Action created to run molecule test cases during any push on develop branch
# The workflow is divided into test stages, based on the PR title particular test stages will run
# The test coverage is for BAF corda and fabric. Other DLTs will be added gradually

name: Docker build baf-build

on:
  push:
    branches: [ docker_build ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: pppazos/baf-build:testci    
