# This is custom git Action created to run molecule test cases during any push on develop branch
# The workflow is divided into test stages, based on the PR title particular test stages will run

name: Docker build baf-build

on:
  create:

jobs:
  docker:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Show GitHub ref
      env:
        TAG: ${{ steps.vars.outputs.tag }}    
      run: |
        echo "$GITHUB_REF"      
        echo "$TAG"  
    -
      name: Build and push release tag ${{ steps.vars.outputs.tag }}  
      id: docker_build_release
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: pppazos/baf-build:tci.${{ steps.vars.outputs.tag }}  
    -
      name: Build and push tag latest
      id: docker_build_latest
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: pppazos/baf-build:tci.latest    
    -
      name: Build and push tag jdk8
      id: docker_build_jdk8
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.jdk8
        push: true
        tags: pppazos/baf-build:tci.jdk8    