# Build baf-build docker image 
# triggered on merge on :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags

#TODO change docker_build to develop

name: Docker image baf-build tagging

on:
  create:
  push:
    branches:
        - docker_build
    paths:
      - 'Dockerfile'        
      - 'Dockerfile.jkd8'        

jobs:
  # on push to develop branch, create docker tags latest and jdk8-latest
  latest:
    if: ${{ startsWith(github.ref, 'refs/heads/docker_build') }}
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push release tag latest
      id: docker_build_latest
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:latest  
    -
      name: Build and push tag jdk8-latest
      id: docker_build_jdk8_latest
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:jdk8-latest   
  # on tag vx.y.z created, create docker tag stable, x.y.z and jdk8
  release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push release tag ${{ steps.vars.outputs.tag }}  
      id: docker_build_release
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:${{ steps.vars.outputs.tag }}    
    -
      name: Build and push release tag stable  based on v${{ steps.vars.outputs.tag }}
      id: docker_build_stable
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:stable          
    -
      name: Build and push tag jdk8-latest
      id: docker_build_jdk8
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile.jdk8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/baf-build:tci.jdk8

